default: fig2 fig3 fig4 fig5 
fig2:
	ln -sf hpo-gene-count.png figure2.png
fig3:
	ln -sf variant_contexts.png figure3.png
fig4:
	ln -sf assay-count-cardio.png figure4.png
fig5:
	ln -sf trans-omics-data-sets.png figure5.png

