---
title: "NIH Funding"
author: "Trang Tran"
date: "3/27/2019"
output: html_document
---

```{r setup, include = FALSE, message = FALSE}
library(magrittr)
library(ggplot2)
library(dplyr)

DATADIR = '../data/nih-funding/'
options(stringsAsFactors = FALSE)
convert_amount <- function(amt_array) {
    sapply(amt_array, function(x) {
        tryCatch({
            as.numeric(x)
        }, error = function(e) {
            message(sprintf("Cannot convert %s to number", x))
            # message(e)
            NA
        }, warning= function(e) {
            message(sprintf("Cannot convert %s to number", x))
            # message(e)
            NA
        }) 
    })
}

nih.cat.cancer = read.table(file.path(DATADIR, 'categories-cancer.txt'), sep = '\t')[[1]]
nih.cat.cvd = read.table(file.path(DATADIR, 'categories-cvd.txt'), sep = '\t')[[1]]
```

## Prepare data

### Load data

```{r}
# all_files = list.files(file.path(DATADIR, 'cancer-cvd'))
all_files = Sys.glob(file.path(DATADIR, 'cancer-cvd', '*', '*.csv'))
all_queries <- all_files %>%
    lapply(function(f) {
        tryCatch({
            data.table::fread(f, sep=',', nThread = 2)
        }, warning= function(e) {
            cat(sprintf("Warning at file %s", f))
            message(e)
            # message(e)
        }, error = function(e) {
            cat(sprintf("Error at file %s", f))
            message(e)
        })
    }) 
good.files <- sapply(all_queries, function(x) length(x) == 10) %>%
    which()
awards.cat <- do.call(rbind, all_queries[good.files])
```

### Re-format

```{r}
awards.cat$Amount.str <- awards.cat$Amount
awards.cat$Amount <- gsub(pattern = "\\D*(\\d+.*)$", replacement = '\\1', x = awards.cat$Amount.str) %>%
    gsub(pattern = ",", replacement = "", x = .) %>%
    as.numeric()
awards.cat <- set_names(awards.cat, c('Category', 'FY', 'FundingIC', 'ProjectNumber', 'SubProjectNumber', 'ProjectTitle', 'PIName', 'OrgName', 'StateCountry', 'Amount', 'Amount.str'))
```

### Cleaning up invalid entries

```{r}
awards.cat <- awards.cat[which(awards.cat$ProjectNumber != ""),]
```

## Analysis

### Cancer vs CVD funding

```{r}
categories = awards.cat$Category %>% unique()
awards.unique = reshape2::dcast(awards.cat[,-c('Amount.str')], FY + FundingIC + ProjectNumber + SubProjectNumber + ProjectTitle + PIName + Amount ~ Category, value.var = 'Category')
# for (x in categories) {
#     awards.unique[,x]  <- ifelse(is.na(awards.unique[[x]]), 0, 1)
# }
str(awards.unique)   
```

Sanity check

```{r}
isCancer = awards.unique[, intersect(nih.cat.cancer, names(awards.unique))] %>% apply(MARGIN = 1, FUN = sum)
isCVD = awards.unique[, intersect(nih.cat.cvd, names(awards.unique))] %>% apply(MARGIN = 1, FUN = sum)
sum(isCancer) + sum(isCVD) == nrow(awards.cat)
```

Calculating total funding

```{r}
MIN_FUNDING = 100
isCancer = awards.unique[awards.unique$Amount > MIN_FUNDING, intersect(nih.cat.cancer, names(awards.unique))] %>% apply(MARGIN = 1, FUN = sum)
isCVD = awards.unique[awards.unique$Amount > MIN_FUNDING, intersect(nih.cat.cvd, names(awards.unique))] %>% apply(MARGIN = 1, FUN = sum)
funding.cancer = awards.unique[isCancer>0,] %>% group_by(FY) %>% summarize(cancer = sum(Amount))
funding.cvd = awards.unique[isCVD>0,] %>% group_by(FY) %>% summarize(cvd = sum(Amount))
funding.total <- merge(x = funding.cancer, y = funding.cvd, by = 'FY') %>%
    set_names(c('Year', 'cancer', 'cardiovascular diseases'))
```

The trends of funding for CVD and cancer research by NIH is shown below, total funding are summed from awards $>\$100$

```{r}
sector.colors = c('cardiovascular diseases' = '#f8766d', 'cancer' = '#c77cff')
funding.total.melted = funding.total %>%
    reshape2::melt(id.vars = 'Year')
p <- ggplot(funding.total.melted) +
    # geom_bar(aes(x = Year, y = value, fill = variable), stat = 'identity', position = 'identity', alpha = 0.3) +
    geom_line(aes(x = Year, y = value, color = variable)) +
    geom_point(aes(x = Year, y = value, color = variable)) +
        xlim(c(2000,2018)) +
        scale_y_continuous(name = 'NIH Funding (dollars)') +
        scale_color_manual(values = sector.colors) +
        geom_text(data = subset(funding.total.melted,Year == '2008'),
              aes(y=value, label=variable, color=variable, x = Year-0.5 ),hjust =1, vjust = 1)  +
        guides(color = FALSE)
print(p)
ggsave(sprintf('nih-funding-min-%s.png', MIN_FUNDING), plot = p, device='png', width = 7, height = 4.5)
```
