---
title: "CVD GEO data sets"
author: "Trang Tran"
date: "9/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rentrez)
library(GEOmetadb)
library(RSQLite)
library(magrittr)
library(dplyr)
library(tidyr)

count_year <- function(year, term) {
    query <- paste(term, "AND (", year, "[PDAT])")
    return(entrez_search(db="pubmed", term=query, retmax =0)$count)
}

get_pmids <- function(query) {
    entrez_search(db="pubmed", term=query, retmax =0)$count %>%
        entrez_search(db="pubmed", term=query, retmax = .) %>%
        `$`('ids') %>%
        return()
}

```

## GEO

### Datasets deposited by CVD publications

```{r}
cardioPubmed <-
    entrez_search(db='pubmed', term=queries['cardiovascular diseases'], retmax=0)$count %>%
    entrez_search(db='pubmed', term=queries['cardiovascular diseases'], retmax=.)
```

GDS is a curated version of GSE, yet becoming deprecated (Sean Davis (NIH)'s answer on Biostar). So we'll stick to GSE.

```{r}
if(!file.exists('GEOmetadb.sqlite')) getSQLiteFile()
con <- dbConnect(SQLite(), 'GEOmetadb.sqlite')

cardio_gsm <- dbGetQuery(con, paste('SELECT gsm.gsm, gsm.source_name_ch1, gsm.organism_ch1, organism_ch2, gpl.gpl, gpl.title as platform, gpl.description as platform_description, technology, gse.gse, gse.submission_date, gse.pubmed_id, gse.title, gse.summary, gse.type',
                      'FROM gse ',
                      'JOIN gse_gsm ON gse.gse = gse_gsm.gse',
                      'JOIN gse_gpl ON gse.gse = gse_gpl.gse',
                      'JOIN gsm ON gse_gsm.gsm = gsm.gsm',
                      'JOIN gpl ON gse_gpl.gpl = gpl.gpl',
                      'WHERE pubmed_id IN (', paste(cardioPubmed$ids,collapse=','), ')'))
```

### Study types

```{r}
types = cardio_gsm$type %>% 
    strsplit(split = ";\t") %>%
    do.call('c',.) %>%
    unique()
technologies = cardio_gsm$technology %>% unique()
cardio_gsm$year <- as.numeric(gsub('^(\\d{4})(.+)$','\\1', cardio_gsm$submission_date))

```

Technology over the years

```{r}

tech_counts <- cardio_gsm %>%
    `$<-`('year', as.numeric(gsub('^(\\d{4})(.+)$','\\1', .$submission_date))) %>%
    subset(TRUE,c('year', 'technology', 'gsm')) %>%
    group_by(year, technology) %>%
    summarize(count = length(year)) %>%
    spread(technology, count) %>%
    reshape2::melt(id.vars='year') %>%
    set_names(c('year', 'technology', 'count'))
tech_counts$count[is.na(tech_counts$count)] = 0
ggplot(tech_counts) +
    # geom_line(aes(x=year,group=technology,color=technology, y=count),alpha=0.5)
    geom_area(aes(x=year,y=count,fill=technology), alpha=0.5, position='stack')
```

GEO Data from human samples over the year

```{r}
cardio_gsm_human <- cardio_gsm %>%
    `$<-`('year', as.numeric(gsub('^(\\d{4})(.+)$','\\1', .$submission_date))) %>%
    subset(grepl('Homo sapiens', .$organism_ch1))
data.table::fwrite(cardio_gsm_human, file='../data/cardio_gsm_human.tsv',sep='\t')
cardio_gsm_human %>%
    subset(TRUE,c('year', 'organism_ch1', 'gsm')) %>%
    ggplot() +
        geom_line(aes(x=year,group=organism_ch1,color=organism_ch1), stat='count',alpha=0.5)
```

```{r}

cardiovascular_gse <- dbGetQuery(con,paste("select gse,type,pubmed_id,summary,title from gse where",
                                           "summary like '%cardiovascular%'", sep=" "))
cardiovascular_gds <- dbGetQuery(con,paste("select gds,pubmed_id,gse,platform_organism,sample_organism,description,title from gds where",
                                            "description like '%cardiovascular%'", sep=" "))
str(cardiovascular_gds)
```